### ISSUE TITLE
EPL fastbuild cfg no longer works

### ISSUE THREAD

**Issue by skribe** [ToxicFrog/misc#2]
G'day mate:

I can't seem to get the mod to work.  I installed via ckan on 1.0.4 and the EPL launcher is still requiring a build time.

Cheers

skribe

**Comment by ToxicFrog** [comment]
It worked for me based on some cursory testing after 1.0.4 came out, but I haven't had a chance to play KSP at all in the last two weeks; the desktop is inaccessible to me and probably will be for a while longer.

You do still need at least one Kerbal in a workshop. The patch works by hugely multiplying how much productivity each one adds, to the point that even massive builds complete in seconds.

If you have a Kerbal, I'm afraid I don't know what the problem could be and don't have any way of testing of investigating at present. Sorry. :(
